[package]
name = "torrent-streamer"
version = "1.0.0"
description = "A desktop application for streaming torrents in real-time"
authors = ["janudax"]
license = "MIT"
edition = "2021"
rust-version = "1.77"

[lib]
name = "torrent_streamer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
librqbit = "8.1.1"
tracing = "0.1"
urlencoding = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
